-- Create the admins table
create table if not exists public.admins (
  id bigint generated by default as identity not null,
  full_name text not null,
  email text not null,
  password text not null, -- Stores hashed password
  avatar_url text null,
  role text null default 'Content Admin'::text,
  permissions text[] null default '{}'::text[],
  last_login timestamp with time zone null,
  avg_time_spent interval null default '00:00:00'::interval,
  status text null default 'Active'::text,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  
  -- 2FA columns
  two_factor_secret text null,
  is_two_factor_enabled boolean default false,

  constraint admins_pkey primary key (id),
  constraint admins_email_key unique (email),
  constraint admins_role_check check (
    (
      role = any (
        array[
          'Super Admin'::text,
          'Content Admin'::text,
          'Support'::text,
          'Viewer'::text,
          'Custom'::text
        ]
      )
    )
  ),
  constraint admins_status_check check (
    (
      status = any (
        array[
          'Active'::text,
          'Invited'::text,
          'Deactivated'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

-- Enable RLS
alter table public.admins enable row level security;

-- Create policies

-- Allow reading admins (for login checks by server actions, although server actions bypass RLS if using service role, but typically client might read profile)
-- Or better, only allow authenticated admins to read other admins or themselves.
create policy "Admins can view all admins"
  on public.admins for select
  using (true); 

-- Only allow insert if authenticated as admin (bootstrapping issue: first admin must be inserted manually or via seed)
create policy "Admins can insert admins"
  on public.admins for insert
  with check (true);

create policy "Admins can update themselves"
  on public.admins for update
  using (true);

-- Insert a default admin for testing (password: admin123)
-- Hash for 'admin123' used here is just a placeholder example, in reality use bcrypt hash.
-- $2a$10$wT0lK.g.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0 (Invalid)
-- We will rely on the signup/seed script or handle separately.
