'use server';

import { supabase } from '@/lib/supabaseClient';
import { revalidatePath } from 'next/cache';

// --- VEHICLES CRUD ---

export async function getVehicles(page = 1, limit = 10, search = '') {
    try {
        const from = (page - 1) * limit;
        const to = from + limit - 1;

        let query = supabase
            .from('vehicles')
            .select('*', { count: 'exact' })
            .range(from, to)
            .order('created_at', { ascending: false });

        if (search) {
            query = query.or(`vehicle_name.ilike.%${search}%,registration_number.ilike.%${search}%`);
        }

        const { data, error, count } = await query;

        if (error) throw error;

        return {
            vehicles: data,
            count,
            totalPages: count ? Math.ceil(count / limit) : 0,
            currentPage: page
        };
    } catch (error: any) {
        console.error('Fetch vehicles error:', error);
        return { vehicles: [], count: 0, totalPages: 0, currentPage: 1, error: error.message };
    }
}

export async function getVehicleById(id: string) {
    try {
        const { data, error } = await supabase
            .from('vehicles')
            .select('*')
            .eq('id', id)
            .single();

        if (error) throw error;
        return { vehicle: data };
    } catch (error: any) {
        console.error('Fetch vehicle by id error:', error);
        return { error: error.message };
    }
}

export async function createVehicle(data: any) {
    try {
        const { id, ...vehicleData } = data; // Ensure unique ID is generated by DB if passed empty

        const { data: newVehicle, error } = await supabase
            .from('vehicles')
            .insert([vehicleData])
            .select()
            .single();

        if (error) throw error;

        revalidatePath('/dashboard/vehicles');
        return { success: true, vehicle: newVehicle };
    } catch (error: any) {
        console.error('Create vehicle error:', error);
        return { success: false, message: error.message };
    }
}

export async function updateVehicle(id: string, data: any) {
    try {
        const { error } = await supabase
            .from('vehicles')
            .update({ ...data, updated_at: new Date().toISOString() })
            .eq('id', id);

        if (error) throw error;

        revalidatePath('/dashboard/vehicles');
        revalidatePath(`/dashboard/vehicles/${id}`);
        return { success: true };
    } catch (error: any) {
        console.error('Update vehicle error:', error);
        return { success: false, message: error.message };
    }
}

export async function deleteVehicle(id: string) {
    try {
        const { error } = await supabase
            .from('vehicles')
            .delete()
            .eq('id', id);

        if (error) throw error;

        revalidatePath('/dashboard/vehicles');
        return { success: true };
    } catch (error: any) {
        console.error('Delete vehicle error:', error);
        return { success: false, message: error.message };
    }
}

// --- DRIVERS CRUD ---

export async function getDrivers(page = 1, limit = 10, search = '') {
    try {
        const from = (page - 1) * limit;
        const to = from + limit - 1;

        let query = supabase
            .from('vehicle_drivers')
            .select('*, vehicles(vehicle_name, registration_number)', { count: 'exact' })
            .range(from, to)
            .order('created_at', { ascending: false });

        if (search) {
            query = query.or(`driver_name.ilike.%${search}%,phone_number.ilike.%${search}%`);
        }

        const { data, error, count } = await query;

        if (error) throw error;

        return {
            drivers: data,
            count,
            totalPages: count ? Math.ceil(count / limit) : 0,
            currentPage: page
        };
    } catch (error: any) {
        console.error('Fetch drivers error:', error);
        return { drivers: [], count: 0, totalPages: 0, currentPage: 1, error: error.message };
    }
}

export async function getDriverById(id: string) {
    try {
        const { data, error } = await supabase
            .from('vehicle_drivers')
            .select('*')
            .eq('id', id)
            .single();

        if (error) throw error;
        return { driver: data };
    } catch (error: any) {
        console.error('Fetch driver by id error:', error);
        return { error: error.message };
    }
}

export async function createDriver(data: any) {
    try {
        const { id, ...driverData } = data;

        // Ensure vehicle_id is null if empty string
        if (driverData.vehicle_id === '') driverData.vehicle_id = null;

        const { data: newDriver, error } = await supabase
            .from('vehicle_drivers')
            .insert([driverData])
            .select()
            .single();

        if (error) throw error;

        revalidatePath('/dashboard/vehicles/drivers');
        return { success: true, driver: newDriver };
    } catch (error: any) {
        console.error('Create driver error:', error);
        return { success: false, message: error.message };
    }
}

export async function updateDriver(id: string, data: any) {
    try {
        // Ensure vehicle_id is null if empty string
        if (data.vehicle_id === '') data.vehicle_id = null;

        const { error } = await supabase
            .from('vehicle_drivers')
            .update(data)
            .eq('id', id);

        if (error) throw error;

        revalidatePath('/dashboard/vehicles/drivers');
        revalidatePath(`/dashboard/vehicles/drivers/${id}`);
        return { success: true };
    } catch (error: any) {
        console.error('Update driver error:', error);
        return { success: false, message: error.message };
    }
}

export async function deleteDriver(id: string) {
    try {
        const { error } = await supabase
            .from('vehicle_drivers')
            .delete()
            .eq('id', id);

        if (error) throw error;

        revalidatePath('/dashboard/vehicles/drivers');
        return { success: true };
    } catch (error: any) {
        console.error('Delete driver error:', error);
        return { success: false, message: error.message };
    }
}

// Helper to get all vehicles for dropdown selection in driver form
export async function getAllVehiclesList() {
    try {
        const { data, error } = await supabase
            .from('vehicles')
            .select('id, vehicle_name, registration_number')
            .eq('is_active', true)
            .order('vehicle_name');

        if (error) throw error;
        return data || [];
    } catch (e) {
        return [];
    }
}
