-- Run this in your Supabase SQL Editor to set up the admin table with a password field

create table if not exists public.admin (
  id bigint generated by default as identity not null,
  email text not null,
  password text not null, -- Storing passwords in plain text is not recommended for production
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint admin_pkey primary key (id),
  constraint admin_email_key unique (email)
) TABLESPACE pg_default;

-- Enable Row Level Security (RLS)
alter table public.admin enable row level security;

-- Create a policy that allows anyone to read (required for the login check to work from the client side)
-- This exposes the password hash (or text) to anyone who knows the API URL, which is very insecure.
-- This is strictly for the requested implementation.
create policy "Allow public read access to admin table"
  on public.admin for select
  using (true);

-- Insert an example admin (replace values as needed)
-- insert into public.admin (email, password) values ('admin@batohi.com', 'admin123');
