-- Admin Table Schema

create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null unique,
  password text not null, -- In production, store HASHED password only!
  avatar_url text,
  role text default 'Content Admin' check (role in ('Super Admin', 'Content Admin', 'Support', 'Viewer')),
  permissions text[] default '{}', -- Array of permission strings e.g. ['manage_users', 'edit_content']
  last_login timestamp with time zone,
  avg_time_spent interval default '0 seconds',
  status text default 'Active' check (status in ('Active', 'Invited', 'Deactivated')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.admins enable row level security;

-- Policies
create policy "Admins can view all admins" on public.admins for select using (true);
create policy "Super Admins can insert/update/delete" on public.admins for all using (true); -- Simplified for dev

-- Realtime
alter publication supabase_realtime add table public.admins;
