    -- Create the 'place_alerts' table
    create table if not exists public.place_alerts (
    id bigint generated by default as identity primary key,
    place_id bigint references public.places(id) on delete cascade not null,
    type text not null, -- 'Crowd', 'Weather', 'Traffic', 'General'
    message text not null,
    severity text default 'Medium', -- 'Low', 'Medium', 'High'
    status text default 'Active', -- 'Active', 'Resolved'
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
    );

    -- Enable RLS
    alter table public.place_alerts enable row level security;

    -- Policies
    create policy "Enable read access for all users" on public.place_alerts for select using (true);
    create policy "Enable insert for authenticated users only" on public.place_alerts for insert with check (true);
    create policy "Enable update for authenticated users only" on public.place_alerts for update using (true);
    create policy "Enable delete for authenticated users only" on public.place_alerts for delete using (true);

    -- Enable Realtime
    alter publication supabase_realtime add table public.place_alerts;
