-- Create the 'places' table if it doesn't exist
create table if not exists public.places (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  category text,
  status text default 'Draft', -- 'Published', 'Draft', 'Archived'
  image_url text, -- simplified for now, could be an array or separate table
  latitude double precision,
  longitude double precision,
  
  -- Labels
  trending boolean default false,
  unesco boolean default false,
  must_visit boolean default false,
  
  distance_from_center text,

  -- Address Details (JSONB)
  -- Structure: { "full": "...", "city": "...", "state": "...", "pincode": "..." }
  address jsonb,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.places enable row level security;

-- Policies
create policy "Enable read access for all users" on public.places for select using (true);
create policy "Enable insert for authenticated users only" on public.places for insert with check (true);
create policy "Enable update for authenticated users only" on public.places for update using (true);
create policy "Enable delete for authenticated users only" on public.places for delete using (true);

-- Enable Realtime
alter publication supabase_realtime add table public.places;
