-- ==========================================
-- Batohi Admin - Full Database Schema v2 (With Realtime)
-- ==========================================

-- 1. Enable UUID extension
create extension if not exists "uuid-ossp";

-- ==========================================
-- Tables
-- ==========================================

-- Table: places
create table if not exists public.places (
    id bigint generated by default as identity primary key,
    name text not null,
    category text,
    status text default 'Draft',
    trending boolean default false,
    unesco boolean default false,
    must_visit boolean default false,
    image_url text,
    images text[],
    description text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: audio_stories
create table if not exists public.audio_stories (
    id uuid default gen_random_uuid() primary key,
    title text not null,
    description text,
    audio_url text not null,
    place_id bigint references public.places(id) on delete set null,
    language text not null,
    transcript text,
    status text default 'Draft',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==========================================
-- ROW LEVEL SECURITY (RLS)
-- ==========================================

alter table public.places enable row level security;
alter table public.audio_stories enable row level security;

create policy "Public read access for places" on public.places for select using (true);
create policy "Auth access for places" on public.places for all using (auth.role() = 'authenticated' or auth.role() = 'anon');

create policy "Public read access for audio_stories" on public.audio_stories for select using (true);
create policy "Auth access for audio_stories" on public.audio_stories for all using (auth.role() = 'authenticated' or auth.role() = 'anon');


-- ==========================================
-- REALTIME REPLICATION (CRITICAL FOR LIVE UPDATES)
-- ==========================================

-- Add tables to the supabase_realtime publication
alter publication supabase_realtime add table public.audio_stories;
alter publication supabase_realtime add table public.places;

-- Table: notifications
create table if not exists public.notifications (
    id uuid default gen_random_uuid() primary key,
    title text not null,
    message text not null,
    type text default 'info', -- 'info', 'warning', 'success', 'event'
    audience text default 'all', -- 'all', 'admins', 'users'
    views integer default 0,
    status text default 'active', -- 'active', 'archived'
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table public.notifications enable row level security;

create policy "Public read access for notifications" on public.notifications for select using (true);
create policy "Auth access for notifications" on public.notifications for all using (auth.role() = 'authenticated' or auth.role() = 'anon');

-- Realtime
alter publication supabase_realtime add table public.notifications;


-- ==========================================
-- STORAGE BUCKETS
-- ==========================================

insert into storage.buckets (id, name, public) values ('audio-stories', 'audio-stories', true) on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('places_media', 'places_media', true) on conflict (id) do nothing;

create policy "Public Read Audio" on storage.objects for select using ( bucket_id = 'audio-stories' );
create policy "Auth Upload Audio" on storage.objects for insert with check ( bucket_id = 'audio-stories' AND (auth.role() = 'authenticated' OR auth.role() = 'anon') );
